# services/pdf_compilation_service.py
import asyncio
import logging
from pathlib import Path
import shutil
import uuid

logger = logging.getLogger(__name__)


async def compile_resume_to_pdf(tailored_content: str) -> bytes:
    """
    Compiles resume LaTeX content to PDF using Tectonic.
    Uses main.tex + resume-content.tex
    """
    logger.info("📄 Starting Tectonic PDF compilation (RESUME)")

    tectonic_path = shutil.which("tectonic")
    if not tectonic_path:
        raise FileNotFoundError("tectonic not found in PATH")

    main_tex_src = Path("data/main.tex")
    if not main_tex_src.exists():
        raise FileNotFoundError("main.tex not found in data/ directory")

    # Create unique temp directory for this run
    run_id = uuid.uuid4().hex[:8]
    tmpdir_path = Path(f"data/tmp_debug_pdf/resume_{run_id}")
    tmpdir_path.mkdir(parents=True, exist_ok=True)

    # Copy main.tex to temp directory
    main_tex_dest = tmpdir_path / "main.tex"
    shutil.copy(main_tex_src, main_tex_dest)

    # Write tailored resume content
    resume_run_path = tmpdir_path / "resume-content.tex"
    resume_run_path.write_text(tailored_content, encoding="utf-8")

    logger.info("▶️ Running tectonic for resume...")
    proc = await asyncio.create_subprocess_exec(
        tectonic_path,
        "--keep-intermediates",
        "--reruns",
        "1",
        "main.tex",
        cwd=tmpdir_path,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()

    if proc.returncode != 0:
        logger.error("Tectonic STDOUT:")
        logger.error(stdout.decode())
        logger.error("Tectonic STDERR:")
        logger.error(stderr.decode())
        raise Exception("Tectonic failed to compile resume PDF")

    # Resume should produce main.pdf
    pdf_path = tmpdir_path / "main.pdf"

    if not pdf_path.exists():
        logger.error("❌ main.pdf was not generated!")
        logger.error("Files in temp directory:")
        for f in tmpdir_path.iterdir():
            logger.error(f"  - {f.name}")
        raise FileNotFoundError(
            "Resume PDF not generated by Tectonic. Check LaTeX syntax in resume-content.tex"
        )

    pdf_bytes = pdf_path.read_bytes()
    logger.info(f"✅ Resume PDF compiled successfully ({len(pdf_bytes)} bytes)")

    # Cleanup temporary files on success
    try:
        shutil.rmtree(tmpdir_path)
    except Exception as e:
        logger.warning(f"Failed to cleanup temp dir {tmpdir_path}: {e}")

    return pdf_bytes


async def compile_cover_letter_to_pdf(tailored_content: str) -> bytes:
    """
    Compiles cover letter LaTeX content to PDF using Tectonic.
    Uses main_CL.tex + CL_content.tex
    """
    logger.info("📄 Starting Tectonic PDF compilation (COVER LETTER)")

    tectonic_path = shutil.which("tectonic")
    if not tectonic_path:
        raise FileNotFoundError("tectonic not found in PATH")

    main_cl_tex_src = Path("data/main_CL.tex")
    if not main_cl_tex_src.exists():
        raise FileNotFoundError("main_CL.tex not found in data/ directory")

    # Create unique temp directory for this run
    run_id = uuid.uuid4().hex[:8]
    tmpdir_path = Path(f"data/tmp_debug_pdf/cl_{run_id}")
    tmpdir_path.mkdir(parents=True, exist_ok=True)

    # Copy main_CL.tex to temp directory
    main_cl_tex_dest = tmpdir_path / "main_CL.tex"
    shutil.copy(main_cl_tex_src, main_cl_tex_dest)

    # Write tailored cover letter content
    cl_run_path = tmpdir_path / "CL_content.tex"
    cl_run_path.write_text(tailored_content, encoding="utf-8")

    logger.info("▶️ Running tectonic for cover letter...")
    proc = await asyncio.create_subprocess_exec(
        tectonic_path,
        "--keep-intermediates",
        "--reruns",
        "1",
        "main_CL.tex",
        cwd=tmpdir_path,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()

    if proc.returncode != 0:
        logger.error("Tectonic STDOUT:")
        logger.error(stdout.decode())
        logger.error("Tectonic STDERR:")
        logger.error(stderr.decode())
        raise Exception("Tectonic failed to compile cover letter PDF")

    # Cover letter should produce main_CL.pdf
    pdf_path = tmpdir_path / "main_CL.pdf"

    if not pdf_path.exists():
        logger.error("❌ main_CL.pdf was not generated!")
        logger.error("Files in temp directory:")
        for f in tmpdir_path.iterdir():
            logger.error(f"  - {f.name}")
        raise FileNotFoundError(
            "Cover letter PDF not generated by Tectonic. Check LaTeX syntax in CL_content.tex"
        )

    pdf_bytes = pdf_path.read_bytes()
    logger.info(f"✅ Cover letter PDF compiled successfully ({len(pdf_bytes)} bytes)")

    # Cleanup temporary files on success
    try:
        shutil.rmtree(tmpdir_path)
    except Exception as e:
        logger.warning(f"Failed to cleanup temp dir {tmpdir_path}: {e}")

    return pdf_bytes
